# Header
menu:
  Home: /
  Archives: /archives
  Blog: /blog
rss: /atom.xml
github: https://github.com/cho0o0
stackoverflow: https://stackoverflow.com/users/6279569/
speakerdeck: https://speakerdeck.com/cho0o0
qiita: https://qiita.com/c-cho

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
  # - category
  # - tag
  - tagcloud
  - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-110320379-1
google_tag_manager: GTM-KSBSTZ3
favicon: /images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

language: default
