version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-hexo-cli
          command: 'sudo npm install -g hexo-cli'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: deploy-public-directory
          command: sudo chmod a+x ./deploy.sh && ./deploy.sh